//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIT.UDLA.FLUJOS.PASANTIAS.DBPersistance.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Queries : global::System.Configuration.ApplicationSettingsBase {
        
        private static Queries defaultInstance = ((Queries)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Queries())));
        
        public static Queries Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM  empresa where emp_id= @emp_id")]
        public string EliminarEmpresa {
            get {
                return ((string)(this["EliminarEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from empresa where emp_id= @emp_id")]
        public string SeleccionarEmpresa {
            get {
                return ((string)(this["SeleccionarEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select *\r\nfrom Persona  where per_matricula=@per_matricula")]
        public string SeleccionarHojaVida {
            get {
                return ((string)(this["SeleccionarHojaVida"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"INSERT INTO [UsuarioEmpresaEvaluacionEstudiante]
           ([Nombre]
           ,[Cedula]
           ,[Cargo]
           ,[AreaTrabajo]
           ,[Funciones]
           ,[FechaInicio]
           ,[FechaFin]
           ,[HorarioTrabajo]
           ,[NumeroHorasEjecutadas])
     VALUES
           (@Nombre
           ,@Cedula
           ,@Cargo
           ,@AreaTrabajo
           ,@Funciones
           ,@FechaInicio
           ,@FechaFin
           ,@HorarioTrabajo
           ,@NumeroHorasEjecutadas)")]
        public string InsertarUsuarioEmpresaEvaluacion {
            get {
                return ((string)(this["InsertarUsuarioEmpresaEvaluacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO Supervisor\r\n          (IdEmpresa ,Nombres ,Area,Telefono ,Email)\r\n   " +
            "  VALUES\r\n (@IdEmpresa ,@Nombres ,@Area ,@Telefono,@Email)")]
        public string InsertarSupervisor {
            get {
                return ((string)(this["InsertarSupervisor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from supervisor where Id= @id")]
        public string SeleccionarSupervisor {
            get {
                return ((string)(this["SeleccionarSupervisor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from supervisor where emp_id= @emp_id")]
        public string SeleccionarSupervisorPorEmpresa {
            get {
                return ((string)(this["SeleccionarSupervisorPorEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM (SELECT TOP (@TamanioPagina) * FROM  (SELECT TOP (@NumeroPagina) * " +
            "FROM Empresa AS T1 ORDER BY emp_id ASC) AS T2 ORDER BY emp_id DESC) T3 ORDER BY " +
            "emp_id ASC ")]
        public string SeleccionarListaEmpresas {
            get {
                return ((string)(this["SeleccionarListaEmpresas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InsertNewEmpresasUser")]
        public string InsertarUsuarioEmpresa {
            get {
                return ((string)(this["InsertarUsuarioEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UpdateEmpresasUser")]
        public string ActualizarUsuarioEmpresa {
            get {
                return ((string)(this["ActualizarUsuarioEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select pert_asig, pert_nive,
            (select asig_prac from aaasig where asig_codi=pert_asig) as asig_prac,
            (select asig_desc from aaasig where asig_codi=pert_asig) as asig_desc,
            (select asig_hpra from aaasig where asig_codi=pert_asig) as asig_hpra,
            (select min(pers_rutp || pers_dve || '|' || trim(pers_nomb) || ' ' || trim(pers_apat)) from aahora,aapara,adpers where hora_asig=pert_asig and hora_secc=1 and hora_anoa=para_anoa and hora_vepe=para_vepe and pers_rutp=hora_prof) as docente
from aapert
where pert_asig=?
")]
        public string SeleccionarMateria {
            get {
                return ((string)(this["SeleccionarMateria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select pert_asig, pert_nive,
            (select asig_prac from aaasig where asig_codi=pert_asig) as asig_prac,
            (select asig_desc from aaasig where asig_codi=pert_asig) as asig_desc,
            (select asig_hpra from aaasig where asig_codi=pert_asig) as asig_hpra,
            (select min(pers_rutp || pers_dve || '|' || trim(pers_nomb) || ' ' || trim(pers_apat)) from aahora,aapara,adpers where hora_asig=pert_asig and hora_secc=1 and hora_anoa=para_anoa and hora_vepe=para_vepe and pers_rutp=hora_prof) as docente
from aapert
where pert_asig=?
")]
        public string SeleccionarMateriaPorId {
            get {
                return ((string)(this["SeleccionarMateriaPorId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select pert_asig, pert_nive,
            (select asig_prac from aaasig where asig_codi=pert_asig) as asig_prac,
            (select asig_desc from aaasig where asig_codi=pert_asig) as asig_desc,
            (select asig_hpra from aaasig where asig_codi=pert_asig) as asig_hpra,
            (select min(pers_rutp || pers_dve || '|' || trim(pers_nomb) || ' ' || trim(pers_apat)) from aahora,aapara,adpers where hora_asig=pert_asig and hora_secc=1 and hora_anoa=para_anoa and hora_vepe=para_vepe and pers_rutp=hora_prof) as docente
from aapert
where pert_carr=?
and pert_plan=?
and pert_espe=?
and pert_asig in (select asig_codi from aaasig where asig_hpra<>0 and asig_prac in ('N','I','F'))")]
        public string SeleccionarListaMaterias {
            get {
                return ((string)(this["SeleccionarListaMaterias"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO Empresa\r\n(emp_ruc\r\n,emp_razon_social\r\n,emp_nombre\r\n,emp_representante" +
            "\r\n,emp_direccion\r\n,emp_telefono)\r\nVALUES\r\n(@emp_ruc\r\n,@emp_razon_social\r\n,@emp_n" +
            "ombre\r\n,@emp_representante\r\n,@emp_direccion\r\n,@emp_telefono)")]
        public string InsertarEmpresa {
            get {
                return ((string)(this["InsertarEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from academico where matricula=@matricula")]
        public string SeleccionarEstudianteSAES {
            get {
                return ((string)(this["SeleccionarEstudianteSAES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select per_matricula from persona where per_matricula=@per_matricula")]
        public string VerificaExistenciaHojaVida {
            get {
                return ((string)(this["VerificaExistenciaHojaVida"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select *\r\nfrom Persona  where per_matricula=@per_matricula")]
        public string HojaVidaEditable {
            get {
                return ((string)(this["HojaVidaEditable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert persona(per_nombres,per_apellidos,per_genero) values(@per_nombres,@per_ape" +
            "llidos,@per_genero)")]
        public string InsertarHojaVidaPrueba {
            get {
                return ((string)(this["InsertarHojaVidaPrueba"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllUsers")]
        public string ObtenerTodosLosUsuarios {
            get {
                return ((string)(this["ObtenerTodosLosUsuarios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllUsersByEmailPaged")]
        public string ObtenerTodosLosUsuariosPorEmailPaginados {
            get {
                return ((string)(this["ObtenerTodosLosUsuariosPorEmailPaginados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllUsersByUserNamePaged")]
        public string ObtenerTodosLosUsuarioPorUsernamePaginados {
            get {
                return ((string)(this["ObtenerTodosLosUsuarioPorUsernamePaginados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllUsersPaged")]
        public string ObtenerTodosLosUsuariosPaginados {
            get {
                return ((string)(this["ObtenerTodosLosUsuariosPaginados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetUserByEmail")]
        public string ObtenerUsuarioPorEmail {
            get {
                return ((string)(this["ObtenerUsuarioPorEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetUserByEmailEmpresa")]
        public string ObtenerUsuarioPorEmailEmpresa {
            get {
                return ((string)(this["ObtenerUsuarioPorEmailEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetUserByUserName")]
        public string ObtenerUsuarioPorUserName {
            get {
                return ((string)(this["ObtenerUsuarioPorUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetUserByUserNameEmpresa")]
        public string ObtenerUsuarioPorUserNameEmpresa {
            get {
                return ((string)(this["ObtenerUsuarioPorUserNameEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetUserByUsernamePassword")]
        public string ObtenerUsuarioPorUserNamePassword {
            get {
                return ((string)(this["ObtenerUsuarioPorUserNamePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetUserByUsernamePasswordEmpresa")]
        public string ObtenerUsuarioPorUserNamePasswordEmpresa {
            get {
                return ((string)(this["ObtenerUsuarioPorUserNamePasswordEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllUsersByEmpPaged")]
        public string ObtenerTodosLosUsuariosPorEmpresasPaginados {
            get {
                return ((string)(this["ObtenerTodosLosUsuariosPorEmpresasPaginados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetUserById")]
        public string ObtenerUsuarioPorID {
            get {
                return ((string)(this["ObtenerUsuarioPorID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetUserByIdEmpresa")]
        public string ObtenerUsuarioEmpresasPorID {
            get {
                return ((string)(this["ObtenerUsuarioEmpresasPorID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllUsersByEmailPagedCount")]
        public string ObtenerTodosLosUsuariosPorEmailPaginadosCount {
            get {
                return ((string)(this["ObtenerTodosLosUsuariosPorEmailPaginadosCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllUsersByUserNamePagedCount")]
        public string ObtenerTodosLosUsuarioPorUsernamePaginadosCount {
            get {
                return ((string)(this["ObtenerTodosLosUsuarioPorUsernamePaginadosCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllUsersPagedCount")]
        public string ObtenerTodosLosUsuariosPaginadosCount {
            get {
                return ((string)(this["ObtenerTodosLosUsuariosPaginadosCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllUsersByEmpPagedCount")]
        public string ObtenerTodosLosUsuariosPorEmpresasPaginadosCount {
            get {
                return ((string)(this["ObtenerTodosLosUsuariosPorEmpresasPaginadosCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UpsertHoras")]
        public string InsertarNotaBE {
            get {
                return ((string)(this["InsertarNotaBE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXECUTE PROCEDURE pasantias_upserthoras(?,?,?,?,?,?,?,?,?,?)")]
        public string InsertarNotaSAES {
            get {
                return ((string)(this["InsertarNotaSAES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT      alum_rut, alum_dv, alum_nmat, alum_carr, alum_plan, alum_espe, alum_jorn,
                  pers_nomb, pers_apat, pers_amat, pers_sexo, pers_eciv, pers_fnac,
                  dire_ciud, dire_dire, dire_fono, dire_fax, dire_mail,
                  (SELECT carr_desl FROM  adcarr where (carr_codi=alum_carr)) AS carr_desl,
                  (SELECT ciud_desc FROM  adciud where (ciud_codi=dire_ciud)) AS ciud_desc,
                  alum_apad, alum_nive
FROM         adalum, adpers, addire, aapara
WHERE     (alum_nmat = ?)  AND (alum_pvig IS NOT NULL) AND (alum_rut = pers_rutp) AND (alum_rut = dire_rutp) AND (dire_tide = '01') AND (alum_apad = para_anoa)
ORDER BY alum_apad DESC, alum_nive DESC")]
        public string SeleccionarAlumno {
            get {
                return ((string)(this["SeleccionarAlumno"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select max(distinct nial_nive) as nial_nive\r\nfrom aanial,aapara\r\nwhere nial_anoa=" +
            "para_anoa\r\nand nial_vepe=DECODE(para_vepe,3,2,para_vepe)\r\nand nial_nmat=?\r\nand n" +
            "ial_carr=?\r\nand nial_plan=?\r\nand nial_espe=?")]
        public string SeleccionarNivel {
            get {
                return ((string)(this["SeleccionarNivel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select pers_rutp, pers_dve, pers_nomb, pers_apat\r\nfrom aatual, aapara, adpers\r\nwh" +
            "ere tual_alum=?\r\nand tual_anoa=para_anoa\r\nand tual_vepe=DECODE(para_vepe,3,2,par" +
            "a_vepe)\r\nand pers_rutp=tual_tuto\r\n")]
        public string SeleccionarTutor {
            get {
                return ((string)(this["SeleccionarTutor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select count(*) as cuarta_matricula from aairre,aapara\r\nwhere irre_anoa=para_anoa" +
            "\r\nand irre_vepe=DECODE(para_vepe,3,2,para_vepe)\r\nand irre_nmat=?\r\nand irre_nvec>" +
            "2\r\n")]
        public string ValidarCuartaMatricula {
            get {
                return ((string)(this["ValidarCuartaMatricula"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXECUTE PROCEDURE obt_cond_matr_carg(?)")]
        public string ValidarDeudas {
            get {
                return ((string)(this["ValidarDeudas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select min(pert_nive)\r\nfrom aapert\r\nwhere pert_carr=?\r\nand pert_plan=?\r\nand pert_" +
            "espe=?\r\nand pert_asig in (select asig_codi from aaasig where asig_hpra<>0)")]
        public string ValidarNivel {
            get {
                return ((string)(this["ValidarNivel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select count(*) as resolucion_retiro from aareso,aapara\r\nwhere reso_anoa=para_ano" +
            "a\r\nand reso_vepe=DECODE(para_vepe,3,2,para_vepe)\r\nand reso_rut=?\r\nand reso_nula=" +
            "\'N\'\r\nand reso_tire=\'AC\'\r\n")]
        public string ValidarResolucionRetiro {
            get {
                return ((string)(this["ValidarResolucionRetiro"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllEmpresasPagedCount")]
        public string ObtenerTodasLasEmpresasCount {
            get {
                return ((string)(this["ObtenerTodasLasEmpresasCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllEmpresasPaged")]
        public string ObtenerTodasLasEmpresasPaginadas {
            get {
                return ((string)(this["ObtenerTodasLasEmpresasPaginadas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from valores where val_tipo=@val_tipo")]
        public string SeleccionarValores {
            get {
                return ((string)(this["SeleccionarValores"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [CAR_ID]\r\n      ,[CAR_NOMBRE]\r\n     \r\n  FROM [CARRERA] where [CAR_TIPO] =1" +
            "")]
        public string SeleccionarCarreras {
            get {
                return ((string)(this["SeleccionarCarreras"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT  [CIU_ID]\r\n      ,[PAI_ID]\r\n      ,[CIU_NOMBRE]\r\n  FROM [CIUDAD] ")]
        public string SeleccionarCiudades {
            get {
                return ((string)(this["SeleccionarCiudades"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT into Persona (PER_NOMBRES,\r\nPER_APELLIDOS,\r\nPER_IDENTIFICACION,\r\nPER_MATRI" +
            "CULA,\r\nPER_DIRECCION,\r\nPER_TELEFONO1,\r\nPER_CELULAR,\r\nPER_CIUDAD,\r\nPER_GENERO,\r\nP" +
            "ER_NACIMIENTO,\r\nPER_MODALIDAD_TRABAJO,\r\nPER_DISPONIBILIDAD,\r\nPER_EMAIL,\r\nPER_CAR" +
            "RERA1,\r\nPER_NIVELC1,\r\nPER_CARRERA2,\r\nPER_NIVELC2,\r\nPER_ESPANOL,\r\nPER_INGLES,\r\nPE" +
            "R_FRANCES,\r\nPER_ALEMAN,\r\nPER_OTRO_IDIOMA,\r\nPER_POIDIOMA,\r\nPER_EMPRESA1,\r\nPER_CAR" +
            "GO1,\r\nPER_REFERENCIA1,\r\nPER_TEL_REF1,\r\nPER_INICIO1,\r\nPER_FIN1,\r\nPER_RESPONSABILI" +
            "DADES1,\r\nPER_EMPRESA2,\r\nPER_CARGO2,\r\nPER_REFERENCIA2,\r\nPER_TEL_REF2,\r\nPER_INICIO" +
            "2,\r\nPER_FIN2,\r\nPER_RESPONSABILIDADES2,\r\nPER_EMPRESA3,\r\nPER_CARGO3,\r\nPER_REFERENC" +
            "IA3,\r\nPER_TEL_REF3,\r\nPER_INICIO3,\r\nPER_FIN3,\r\nPER_RESPONSABILIDADES3,\r\nper_nivel" +
            "_empleo, \r\nper_aspiracion, \r\nper_objetivo, \r\nper_meritos, per_actividades,\r\nper_" +
            "institucion,\r\nper_estudios,\r\nper_nivelestudios,\r\nper_lugar,\r\nper_clase_empleo,\r\n" +
            "PER_FECHA_CREACION)\r\n VALUES(\r\n@PER_NOMBRES,\r\n@PER_APELLIDOS,\r\n@PER_IDENTIFICACI" +
            "ON,\r\n@PER_MATRICULA,\r\n@PER_DIRECCION,\r\n@PER_TELEFONO1,\r\n@PER_CELULAR,\r\n@PER_CIUD" +
            "AD,\r\n@PER_GENERO,\r\n@PER_NACIMIENTO,\r\n@PER_MODALIDAD_TRABAJO,\r\n@PER_DISPONIBILIDA" +
            "D,\r\n@PER_EMAIL,\r\n@PER_CARRERA1,\r\n@PER_NIVELC1,\r\n@PER_CARRERA2,\r\n@PER_NIVELC2,\r\n@" +
            "PER_ESPANOL,\r\n@PER_INGLES,\r\n@PER_FRANCES,\r\n@PER_ALEMAN,\r\n@PER_OTRO_IDIOMA,\r\n@PER" +
            "_OTRO_IDIOMA_VALOR,\r\n@PER_EMPRESA1,\r\n@PER_CARGO1,\r\n@PER_REFERENCIA1,\r\n@PER_TEL_R" +
            "EF1,\r\n@PER_INICIO1,\r\n@PER_FIN1,\r\n@PER_RESPONSABILIDADES1,\r\n@PER_EMPRESA2,\r\n@PER_" +
            "CARGO2,\r\n@PER_REFERENCIA2,\r\n@PER_TEL_REF2,\r\n@PER_INICIO2,\r\n@PER_FIN2,\r\n@PER_RESP" +
            "ONSABILIDADES2,\r\n@PER_EMPRESA3,\r\n@PER_CARGO3,\r\n@PER_REFERENCIA3,\r\n@PER_TEL_REF3," +
            "\r\n@PER_INICIO3,\r\n@PER_FIN3,\r\n@PER_RESPONSABILIDADES3,\r\n@per_nivel_empleo, \r\n@per" +
            "_aspiracion, \r\n@per_objetivo, \r\n@per_meritos, @per_actividades,\r\n@per_institucio" +
            "n,\r\n@per_estudios,\r\n@per_nivelestudios,\r\n@per_lugar,\r\n@per_clase_empleo,\r\n@per_f" +
            "echa_creacion\r\n)")]
        public string InsertarHojaVida {
            get {
                return ((string)(this["InsertarHojaVida"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("update persona set PER_NOMBRES=@PER_NOMBRES,\r\nPER_APELLIDOS=@PER_APELLIDOS,\r\nPER_" +
            "IDENTIFICACION=@PER_IDENTIFICACION,\r\nPER_MATRICULA=@PER_MATRICULA,\r\nPER_DIRECCIO" +
            "N=@PER_DIRECCION,\r\nPER_TELEFONO1=@PER_TELEFONO1,\r\nPER_CELULAR=@PER_CELULAR,\r\nPER" +
            "_CIUDAD=@PER_CIUDAD,\r\nPER_GENERO=@PER_GENERO,\r\nPER_NACIMIENTO=@PER_NACIMIENTO,\r\n" +
            "PER_MODALIDAD_TRABAJO=@PER_MODALIDAD_TRABAJO,\r\nPER_DISPONIBILIDAD=@PER_DISPONIBI" +
            "LIDAD,\r\nPER_EMAIL=@PER_EMAIL,\r\nPER_CARRERA1=@PER_CARRERA1,\r\nPER_NIVELC1=@PER_NIV" +
            "ELC1,\r\nPER_CARRERA2=@PER_CARRERA2,\r\nPER_NIVELC2=@PER_NIVELC2,\r\nPER_ESPANOL=@PER_" +
            "ESPANOL,\r\nPER_INGLES=@PER_INGLES,\r\nPER_FRANCES=@PER_FRANCES,\r\nPER_ALEMAN=@PER_AL" +
            "EMAN,\r\nPER_OTRO_IDIOMA=@PER_OTRO_IDIOMA,\r\nPER_EMPRESA1=@PER_EMPRESA1,\r\nPER_CARGO" +
            "1=@PER_CARGO1,\r\nPER_REFERENCIA1=@PER_REFERENCIA1,\r\nPER_TEL_REF1=@PER_TEL_REF1,\r\n" +
            "PER_INICIO1=@PER_INICIO1,\r\nPER_FIN1=@PER_FIN1,\r\nPER_RESPONSABILIDADES1=@PER_RESP" +
            "ONSABILIDADES1,\r\nPER_EMPRESA2=@PER_EMPRESA2,\r\nPER_CARGO2=@PER_CARGO2,\r\nPER_REFER" +
            "ENCIA2=@PER_REFERENCIA2,\r\nPER_TEL_REF2=@PER_TEL_REF2,\r\nPER_INICIO2=@PER_INICIO2," +
            "\r\nPER_FIN2=@PER_FIN2,\r\nPER_RESPONSABILIDADES2=@PER_RESPONSABILIDADES2,\r\nPER_EMPR" +
            "ESA3=@PER_EMPRESA3,\r\nPER_CARGO3=@PER_CARGO3,\r\nPER_REFERENCIA3=@PER_REFERENCIA3,\r" +
            "\nPER_TEL_REF3=@PER_TEL_REF3,\r\nPER_INICIO3=@PER_INICIO3,\r\nPER_FIN3=@PER_FIN3,\r\nPE" +
            "R_RESPONSABILIDADES3=@PER_RESPONSABILIDADES3, \r\nPER_POIDIOMA=@PER_OTRO_IDIOMA_VA" +
            "LOR,\r\nper_aspiracion=@per_aspiracion,\r\nper_nivel_empleo=@per_nivel_empleo,\r\nper_" +
            "meritos=@per_meritos,\r\nper_objetivo=@per_objetivo,\r\nper_actividades=@per_activid" +
            "ades,\r\nper_institucion=@per_institucion, \r\nper_estudios=@per_estudios, \r\nper_niv" +
            "elestudios=@per_nivelestudios,\r\nper_lugar=@per_lugar,\r\nper_clase_empleo=@per_cla" +
            "se_empleo,\r\nper_fecha_actualizacion=@per_fecha_actualizacion\r\nwhere PER_MATRICUL" +
            "A=@PER_MATRICULA")]
        public string ActualizarHojaVida {
            get {
                return ((string)(this["ActualizarHojaVida"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select sum(prac_hora) from aaprac\r\nwhere prac_nmat = @p1\r\nand prac_mate = @p2")]
        public string SettingConsultarNotaBE {
            get {
                return ((string)(this["SettingConsultarNotaBE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select sum(prac_hora) from aaprac\r\nwhere prac_nmat = ?\r\nand prac_mate = ?")]
        public string ConsultarNotaSAES {
            get {
                return ((string)(this["ConsultarNotaSAES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select sum(prac_hora) from aaprac\r\nwhere prac_nmat = @p1\r\nand prac_mate = @p2")]
        public string ConsultarNotaBE {
            get {
                return ((string)(this["ConsultarNotaBE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"INSERT INTO CURSOS
           (PER_ID
           ,PAI_ID
           ,CUR_INSTITUCION
           ,CUR_NOMBRE
           ,CUR_FECHA_INICIO
           ,CUR_DURACION
           ,CUR_DESCRIPCION
           ,CUR_ESTADO)
     VALUES
           (@PER_ID
           ,@PAI_ID
           ,@CUR_INSTITUCION
           ,@CUR_NOMBRE
           ,@CUR_FECHA_INICIO
           ,@CUR_DURACION
           ,@CUR_DESCRIPCION
           ,@CUR_ESTADO)")]
        public string InsertarCurso {
            get {
                return ((string)(this["InsertarCurso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"UPDATE CURSOS
   SET PER_ID =@PER_ID
      ,PAI_ID =@PAI_ID
      ,CUR_INSTITUCION =@CUR_INSTITUCION
      ,CUR_NOMBRE =@CUR_NOMBRE
      ,CUR_FECHA_INICIO =@CUR_FECHA_INICIO
      ,CUR_DURACION =@CUR_DURACION
      ,CUR_DESCRIPCION =@CUR_DESCRIPCION
      ,CUR_ESTADO =@CUR_ESTADO
 WHERE cur_id=@cur_id")]
        public string ActualizarCurso {
            get {
                return ((string)(this["ActualizarCurso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [CUR_ID]\r\n      ,[PER_ID]\r\n      ,[PAI_ID]\r\n      ,[CUR_INSTITUCION]\r\n    " +
            "  ,[CUR_NOMBRE]\r\n      ,[CUR_FECHA_INICIO]\r\n      ,[CUR_DURACION]\r\n      ,[CUR_D" +
            "ESCRIPCION]\r\n      ,[CUR_ESTADO]\r\n  FROM [CURSOS] where cur_id=@cur_id and per_i" +
            "d=@per_id")]
        public string SeleccionarCurso {
            get {
                return ((string)(this["SeleccionarCurso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select CUR_ID from Curso where CUR_ID=@CUR_ID")]
        public string VerificarExistenciaCurso {
            get {
                return ((string)(this["VerificarExistenciaCurso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SeleccionarCursosPorPersona {
            get {
                return ((string)(this["SeleccionarCursosPorPersona"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from cursos where per_id=@per_id")]
        public string ObtenerTodosLosCursosPorPersona {
            get {
                return ((string)(this["ObtenerTodosLosCursosPorPersona"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("delete cursos where cur_id=@cur_id")]
        public string EliminarCurso {
            get {
                return ((string)(this["EliminarCurso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllOfertasPaged")]
        public string ObtenerOfertarPaginado {
            get {
                return ((string)(this["ObtenerOfertarPaginado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetAllOfertasPagedCount")]
        public string ObtenerOfertasPaginadoCount {
            get {
                return ((string)(this["ObtenerOfertasPaginadoCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetOfertasByOfeID")]
        public string ObtenerOfertasPorId {
            get {
                return ((string)(this["ObtenerOfertasPorId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserValidOferta")]
        public string ValidarOfertaPorUsuario {
            get {
                return ((string)(this["ValidarOfertaPorUsuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO aplicacion_oferta\r\n                  (ofe_id, per_id)\r\n              " +
            "  VALUES\r\n                  (@oferta_id, @persona_id)")]
        public string InsertarOferta {
            get {
                return ((string)(this["InsertarOferta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT \r\n      [CAR_BE]\r\n      ,[CAR_SAES_NOMBRE]\r\n  FROM [CARRERA_SAES_BE] where" +
            "  [CAR_SAES] =@SAES")]
        public string SeleccionCarreraSAESBolsaEmpleo {
            get {
                return ((string)(this["SeleccionCarreraSAESBolsaEmpleo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                  SELECT  [PAI_ID]\r\n                  ,[PAI_NOMBRE]\r\n          " +
            "        FROM [PAIS] order by [PAI_NOMBRE]\r\n                ")]
        public string SeleccionarPaises {
            get {
                return ((string)(this["SeleccionarPaises"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select carg_asig,
         (select asig_prac from aaasig where asig_codi=carg_asig) as asig_prac,
         (select asig_desc from aaasig where asig_codi=carg_asig) as asig_desc,
         (select asig_hpra from aaasig where asig_codi=carg_asig) as asig_hpra,
         (select min(pers_rutp || pers_dve || '|' || trim(pers_nomb) || ' ' || trim(pers_apat)) from aahora,aapara,adpers where hora_asig=carg_asig and hora_secc=1 and hora_anoa=para_anoa and hora_vepe=para_vepe and pers_rutp=hora_prof) as docente
from aacarg, aaasig, aapara
where carg_anoa = para_anoa
and carg_vepe = para_vepe
and carg_nmat = ?
and carg_asig= asig_codi
and asig_hpra is not null")]
        public string SeleccionarListaMateriasSupervision {
            get {
                return ((string)(this["SeleccionarListaMateriasSupervision"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select carg_asig,
         (select asig_prac from aaasig where asig_codi=carg_asig) as asig_prac,
         (select asig_desc from aaasig where asig_codi=carg_asig) as asig_desc,
         (select asig_hpra from aaasig where asig_codi=carg_asig) as asig_hpra,
         (select min(pers_rutp || pers_dve || '|' || trim(pers_nomb) || ' ' || trim(pers_apat)) from aahora,aapara,adpers where  hora_asig=carg_asig and hora_secc=1 and hora_anoa=para_anoa and hora_vepe=para_vepe and pers_rutp=hora_prof) as docente
from aacarg
where carg_asig=?
and carg_nmat=?")]
        public string SeleccionarMateriaPorIdSupervision {
            get {
                return ((string)(this["SeleccionarMateriaPorIdSupervision"]));
            }
        }
    }
}
