//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIT.UDLA.FLUJO.PASANTIAS.WebParts.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Pages : global::System.Configuration.ApplicationSettingsBase {
        
        private static Pages defaultInstance = ((Pages)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Pages())));
        
        public static Pages Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_layouts/Dialogs/NuevaVisita.aspx")]
        public string RegistroVisitas {
            get {
                return ((string)(this["RegistroVisitas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_layouts/Dialogs/NuevaActividad.aspx")]
        public string RegistroActividades {
            get {
                return ((string)(this["RegistroActividades"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/Mensaje.aspx")]
        public string MensajePageName {
            get {
                return ((string)(this["MensajePageName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/SeleccionDeTipoDePractica.aspx")]
        public string SeleccionPractica {
            get {
                return ((string)(this["SeleccionPractica"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/HojaDeVida.aspx")]
        public string HojaDeVida {
            get {
                return ((string)(this["HojaDeVida"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/SeleccionEmpresas.aspx")]
        public string Empresas {
            get {
                return ((string)(this["Empresas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_layouts/BIT.UDLA.FLUJO.PASANTIAS.WebParts/Pasantias-Pre-Profesionales.aspx")]
        public string PaginaInformacion {
            get {
                return ((string)(this["PaginaInformacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/ConSupervision.aspx")]
        public string ConSupervision {
            get {
                return ((string)(this["ConSupervision"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/EvaluacionTutor.aspx")]
        public string EvaluacionFinal {
            get {
                return ((string)(this["EvaluacionFinal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/SeleccionDeMateria.aspx")]
        public string SeleccionMateria {
            get {
                return ((string)(this["SeleccionMateria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/SeleccionAlumnoDocente.aspx")]
        public string SeleccionAlumnosDocente {
            get {
                return ((string)(this["SeleccionAlumnosDocente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Supervisores/SeleccionSupervisorEmpresas.aspx")]
        public string SeleccionUsuarioEmpresa {
            get {
                return ((string)(this["SeleccionUsuarioEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Empresas/SeleccionAlumnoEmpresa.aspx")]
        public string SeleccionAlumnosEmpresa {
            get {
                return ((string)(this["SeleccionAlumnosEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Empresas/FichaRegistro.aspx")]
        public string FichaRegistroEmpresa {
            get {
                return ((string)(this["FichaRegistroEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Encuestas/EvaluacionEmpresas.aspx")]
        public string EvaluacionEmpresa {
            get {
                return ((string)(this["EvaluacionEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Encuestas/EvaluacionAlumnos.aspx")]
        public string EvaluacionEstudiante {
            get {
                return ((string)(this["EvaluacionEstudiante"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/MensajeError.aspx")]
        public string Error {
            get {
                return ((string)(this["Error"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_layouts/Dialogs/NuevoUsuario.aspx")]
        public string RegistroUsuarios {
            get {
                return ((string)(this["RegistroUsuarios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/FichaRegistroTutor.aspx")]
        public string FichaRegistroTutor {
            get {
                return ((string)(this["FichaRegistroTutor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Empresas/FichaRegistroConfirmacionEmpresa.aspx")]
        public string FichaRegistroConfirmacionEmpresa {
            get {
                return ((string)(this["FichaRegistroConfirmacionEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_layouts/BIT.UDLA.FLUJO.PASANTIAS.WebParts/actionPage.aspx")]
        public string Accion {
            get {
                return ((string)(this["Accion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Empresas/RouterEmpresas.aspx")]
        public string RouterPagina {
            get {
                return ((string)(this["RouterPagina"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Home {
            get {
                return ((string)(this["Home"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/EnProceso.aspx")]
        public string EnProceso {
            get {
                return ((string)(this["EnProceso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_layouts/Dialogs/NuevoCurso.aspx")]
        public string RegistroCurso {
            get {
                return ((string)(this["RegistroCurso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/Cursos.aspx")]
        public string Cursos {
            get {
                return ((string)(this["Cursos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/SeleccionOfertas.aspx")]
        public string Ofertas {
            get {
                return ((string)(this["Ofertas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/TipoEmpresasOfertas.aspx")]
        public string RutaEmpresaOfertas {
            get {
                return ((string)(this["RutaEmpresaOfertas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sntest06:8082/PaginasPracticasPreProfesionales/Empresas/Empresas.aspx")]
        public string EmpresasPuerto {
            get {
                return ((string)(this["EmpresasPuerto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/CancelarPractica.aspx")]
        public string CancelarPractica {
            get {
                return ((string)(this["CancelarPractica"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_layouts/Cancelar/CancelarFlujo.aspx")]
        public string ConfirmarCancelacion {
            get {
                return ((string)(this["ConfirmarCancelacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/EnProceso.aspx")]
        public string Finalizada {
            get {
                return ((string)(this["Finalizada"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/InformacionEmpresas.aspx")]
        public string InformacionEmpresas {
            get {
                return ((string)(this["InformacionEmpresas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Practicas/NuevaEmpresa.aspx")]
        public string NuevaEmpresa {
            get {
                return ((string)(this["NuevaEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Directo/Docentes.aspx")]
        public string IrADocente {
            get {
                return ((string)(this["IrADocente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaginasPracticasPreProfesionales/Empresas/Empresas.aspx")]
        public string IrAEmpresa {
            get {
                return ((string)(this["IrAEmpresa"]));
            }
        }
    }
}
