//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIT.UDLA.FLUJOS.PASANTIAS.Constants.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Connectors : global::System.Configuration.ApplicationSettingsBase {
        
        private static Connectors defaultInstance = ((Connectors)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Connectors())));
        
        public static Connectors Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=SAES")]
        public string SAES {
            get {
                return ((string)(this["SAES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SNTEST01\\SQL2K5;Initial Catalog=BolsaEmpleo_Test;Persist Security Inf" +
            "o=True;User ID=sa;Password=123456")]
        public string Backup {
            get {
                return ((string)(this["Backup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.4.45;Database=BolsaEmpleo_Test;User ID=sa;Password=123456;Trusted_" +
            "Connection=False;")]
        public string BEmpleo {
            get {
                return ((string)(this["BEmpleo"]));
            }
        }
    }
}
