//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIT.UDLA.FLUJOS.PASANTIAS.Constants.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Flujo : global::System.Configuration.ApplicationSettingsBase {
        
        private static Flujo defaultInstance = ((Flujo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Flujo())));
        
        public static Flujo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INICIO")]
        public string INICIO {
            get {
                return ((string)(this["INICIO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACTUALIZACION_HOJA_DE_VIDA")]
        public string ACTUALIZACION_HOJA_DE_VIDA {
            get {
                return ((string)(this["ACTUALIZACION_HOJA_DE_VIDA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EMPRESA_SELECCIONADA")]
        public string EMPRESA_SELECCIONADA {
            get {
                return ((string)(this["EMPRESA_SELECCIONADA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECCION_USUARIO_DOCENTE")]
        public string SELECCION_USUARIO_DOCENTE {
            get {
                return ((string)(this["SELECCION_USUARIO_DOCENTE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECCION_USUARIO_EMPRESA")]
        public string SELECCION_USUARIO_EMPRESA {
            get {
                return ((string)(this["SELECCION_USUARIO_EMPRESA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACEPTACION_ESTUDIANTE_EMPRESA")]
        public string ACEPTACION_ESTUDIANTE_EMPRESA {
            get {
                return ((string)(this["ACEPTACION_ESTUDIANTE_EMPRESA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ASIGNACION_EMPRESA")]
        public string ASIGNACION_EMPRESA {
            get {
                return ((string)(this["ASIGNACION_EMPRESA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REVISION_TUTOR")]
        public string REVISION_TUTOR {
            get {
                return ((string)(this["REVISION_TUTOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CONFIRMACION_EMPRESA")]
        public string CONFIRMACION_EMPRESA {
            get {
                return ((string)(this["CONFIRMACION_EMPRESA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REGISTRO_TUTOR")]
        public string REGISTRO_TUTOR {
            get {
                return ((string)(this["REGISTRO_TUTOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EDICION_ESTUDIANTE_EMPRESA")]
        public string EDICION_ESTUDIANTE_EMPRESA {
            get {
                return ((string)(this["EDICION_ESTUDIANTE_EMPRESA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECCION_MATERIA")]
        public string SELECCION_MATERIA {
            get {
                return ((string)(this["SELECCION_MATERIA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CANCELADO")]
        public string CANCELADO {
            get {
                return ((string)(this["CANCELADO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FINALIZADO")]
        public string FINALIZACION {
            get {
                return ((string)(this["FINALIZACION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CARTA_DE_COMPROMISO")]
        public string CARTA_DE_COMPROMISO {
            get {
                return ((string)(this["CARTA_DE_COMPROMISO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EMPRESA_EN_PROCESO")]
        public string EMPRESA_EN_PROCESO {
            get {
                return ((string)(this["EMPRESA_EN_PROCESO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOTIFICAR_DOCENTE")]
        public string NOTIFICAR_DOCENTE {
            get {
                return ((string)(this["NOTIFICAR_DOCENTE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECCION_PRACTICA")]
        public string SELECCION_PRACTICA {
            get {
                return ((string)(this["SELECCION_PRACTICA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOTIFICAR_USUARIO_EMPRESA")]
        public string NOTIFICAR_USUARIO_EMPRESA {
            get {
                return ((string)(this["NOTIFICAR_USUARIO_EMPRESA"]));
            }
        }
    }
}
