//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIT.UDLA.FLUJOS.PASANTIAS.MossPersistance.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class UdlaListDefinitions : global::System.Configuration.ApplicationSettingsBase {
        
        private static UdlaListDefinitions defaultInstance = ((UdlaListDefinitions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UdlaListDefinitions())));
        
        public static UdlaListDefinitions Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empresas")]
        public string Lista_Empresas {
            get {
                return ((string)(this["Lista_Empresas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lista Pasantias")]
        public string Lista_Pasantias {
            get {
                return ((string)(this["Lista_Pasantias"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sntest05:84")]
        public string Url_Sitio {
            get {
                return ((string)(this["Url_Sitio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lista Visitas")]
        public string Lista_Visitas {
            get {
                return ((string)(this["Lista_Visitas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lista de Actividades Por Estudiante")]
        public string Lista_Actividades {
            get {
                return ((string)(this["Lista_Actividades"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lista Usuarios")]
        public string Lista_Usuarios {
            get {
                return ((string)(this["Lista_Usuarios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sntest05:84")]
        public string Url_Proceso {
            get {
                return ((string)(this["Url_Proceso"]));
            }
        }
    }
}
